/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessmanagersystem;

import static fitnessmanagersystem.AddAdministrator1.jCheckBox_dataAdmin;
import static fitnessmanagersystem.AddAdministrator1.jComboBox_City;
import static fitnessmanagersystem.AddAdministrator1.jComboBox_Sex;
import static fitnessmanagersystem.AddAdministrator1.jTextArea_info;
import static fitnessmanagersystem.AddAdministrator1.jTextField_AdminAge;
import static fitnessmanagersystem.AddAdministrator1.jTextField_Email;
import static fitnessmanagersystem.AddAdministrator1.jTextField_Street;
import static fitnessmanagersystem.AddAdministrator1.jTextField_Telephone;
import static fitnessmanagersystem.AddAdministrator1.jTextField_fNameAdmin;
import static fitnessmanagersystem.AddAdministrator1.jTextField_lNameAdmin;
import static fitnessmanagersystem.AddAdministrator1.jTextField_middleName;
import static fitnessmanagersystem.GUI.Panel11;
import java.awt.BorderLayout;
import java.awt.Color;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author DISHLIEV
 */
public class AddProduct extends javax.swing.JPanel {

    /**
     * Creates new form AddProduct
     */
    public AddProduct() {
        initComponents();
    }
      
      public void changed() {
     
     if (jTextField_IdProducts.getText().equals("")||
         jTextField_Name.getText().equals("")||
         jTextField_Brand.getText().equals("")||
         jTextArea_Information.getText().equals("")||
         jTextField_Pieces.getText().equals("")||
         jTextField_Price.getText().equals("")
       
             ){
       jButton_save.setEnabled(false);
     }
     else {
       jButton_save.setEnabled(true);
    }
}
      
  public Connection getConnection()
   {
       Connection con;
    
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system?characterEncoding=utf8", "root","");
           
           return con;
       } catch (Exception e) {
           return null;
       }
   }
     public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
   
       try{
       
           st = con.createStatement();
          if((st.executeUpdate(query)) == 1)
          {

               jLabel9dsfgbsdfgbsdfg.setText("Продукта е въведен успешно.");
                jLabel9dsfgbsdfgbsdfg.setForeground(Color.GREEN);
                
              jTextField_IdProducts.setEditable(false);
                      jTextField_Name.setEditable(false);
                      jTextField_Brand.setEditable(false);
                              JComboBox_Category.setEditable(false);
                              jTextArea_Information.setEditable(false);
                                      jTextField_Pieces.setEditable(false);
                                      jTextField_Price.setEditable(false);
                                             
                                              
                                              jButton_save.setEnabled(false);
           }else{
               jLabel9dsfgbsdfgbsdfg.setText("Продукта не е въведен успешно.");
                jLabel9dsfgbsdfgbsdfg.setForeground(Color.RED);
          }
       }catch(SQLException | HeadlessException ex){
       }
   }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
   
    
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea_Information = new javax.swing.JTextArea();
        jTextField_Name = new javax.swing.JTextField();
        jTextField_Brand = new javax.swing.JTextField();
        jButton_save = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        JComboBox_Category = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jTextField_IdProducts = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_Pieces = new javax.swing.JTextField();
        jTextField_Price = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        jLabel9dsfgbsdfgbsdfg = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        jTextArea_Information.setColumns(20);
        jTextArea_Information.setRows(5);
        jTextArea_Information.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextArea_InformationKeyTyped(evt);
            }
        });
        jScrollPane1.setViewportView(jTextArea_Information);

        jTextField_Name.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_NameKeyTyped(evt);
            }
        });

        jTextField_Brand.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_BrandKeyTyped(evt);
            }
        });

        jButton_save.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\gnome_media_floppy.png")); // NOI18N
        jButton_save.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton_saveActionPerformed(evt);
            }
        });

        jLabel1.setText("Име:");

        jLabel2.setText("Марка:");

        jLabel3.setText("Информация:");

        jLabel4.setText("Категория:");

        JComboBox_Category.setEditable(true);
        JComboBox_Category.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Протеини", "Аминокиселини", "Азотни бустери", "Витамини и минерали" }));
        JComboBox_Category.setAutoscrolls(true);
        JComboBox_Category.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        JComboBox_Category.setFocusCycleRoot(true);

        jLabel5.setText("ID номер:");

        jTextField_IdProducts.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_IdProductsKeyTyped(evt);
            }
        });

        jLabel6.setText("Бройки:");

        jLabel7.setText("Цена на бройка:");

        jTextField_Pieces.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PiecesKeyTyped(evt);
            }
        });

        jTextField_Price.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_PriceKeyTyped(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\cancel.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\refresh.png")); // NOI18N
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jScrollPane1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton_save)
                                        .addGap(18, 18, 18)
                                        .addComponent(jButton2))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(55, 55, 55)
                                        .addComponent(jButton1)))
                                .addGap(29, 29, 29))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_Name, javax.swing.GroupLayout.DEFAULT_SIZE, 168, Short.MAX_VALUE)
                                    .addComponent(jTextField_Brand)
                                    .addComponent(JComboBox_Category, 0, 168, Short.MAX_VALUE)
                                    .addComponent(jTextField_IdProducts))
                                .addGap(99, 99, 99)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(jTextField_Pieces, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                                    .addComponent(jTextField_Price))
                                .addContainerGap(249, Short.MAX_VALUE))))))
            .addGroup(layout.createSequentialGroup()
                .addGap(212, 212, 212)
                .addComponent(jLabel9dsfgbsdfgbsdfg, javax.swing.GroupLayout.PREFERRED_SIZE, 346, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextField_IdProducts, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(jTextField_Pieces, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jTextField_Name, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel1)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(jTextField_Price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(17, 17, 17)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_Brand, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(JComboBox_Category, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(42, 42, 42)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton_save)
                            .addComponent(jButton2))
                        .addGap(69, 69, 69))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 243, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9dsfgbsdfgbsdfg, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButton_saveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton_saveActionPerformed
       String query =
        "INSERT INTO `products`(`id`,`name`, `brand`, `category`,`information`, `pieces`, `price`) VALUES ('"+jTextField_IdProducts.getText()+"','"+jTextField_Name.getText()+"','"+jTextField_Brand.getText()+"','"+JComboBox_Category.getSelectedItem().toString()+"','"+jTextArea_Information.getText()+"','"+jTextField_Pieces.getText()+"','"+jTextField_Price.getText()+"')"; 
        executeSQlQuery(query, "");
    }//GEN-LAST:event_jButton_saveActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        HomePanel p1 = new HomePanel();
                            p1.setSize(949, 100);
                            p1.setLocation(0, 0);
                            
                            Panel11.setLayout(new GridLayout(0,1));
                            Panel11.removeAll();
                            Panel11.add(p1,BorderLayout.PAGE_END);
                            Panel11.revalidate();
                            Panel11.repaint();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField_IdProductsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_IdProductsKeyTyped

        
        
        
        jTextField_IdProducts.getDocument().addDocumentListener(new DocumentListener() {
  @Override
  public void changedUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void removeUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void insertUpdate(DocumentEvent e) {
    changed();
  }});
    }//GEN-LAST:event_jTextField_IdProductsKeyTyped

    private void jTextField_NameKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_NameKeyTyped
          jTextField_Name.getDocument().addDocumentListener(new DocumentListener() {
  @Override
  public void changedUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void removeUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void insertUpdate(DocumentEvent e) {
    changed();
  }});
    }//GEN-LAST:event_jTextField_NameKeyTyped

    private void jTextField_BrandKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_BrandKeyTyped
           jTextField_Brand.getDocument().addDocumentListener(new DocumentListener() {
  @Override
  public void changedUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void removeUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void insertUpdate(DocumentEvent e) {
    changed();
  }});
    }//GEN-LAST:event_jTextField_BrandKeyTyped

    private void jTextArea_InformationKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextArea_InformationKeyTyped
           jTextArea_Information.getDocument().addDocumentListener(new DocumentListener() {
  @Override
  public void changedUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void removeUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void insertUpdate(DocumentEvent e) {
    changed();
  }});
    }//GEN-LAST:event_jTextArea_InformationKeyTyped

    private void jTextField_PiecesKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PiecesKeyTyped
 if(jTextField_Pieces.getText().length()>=5) {
            getToolkit().beep(); //издава звук
            evt.consume();
        }
        //ограничение да се въвеждат само цифри
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            getToolkit().beep();  //издава звук при въвеждане на буква
            evt.consume();

        }
        
        
        
        jTextField_Pieces.getDocument().addDocumentListener(new DocumentListener() {
  @Override
  public void changedUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void removeUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void insertUpdate(DocumentEvent e) {
    changed();
  }});
    }//GEN-LAST:event_jTextField_PiecesKeyTyped

    private void jTextField_PriceKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_PriceKeyTyped
 if(jTextField_Price.getText().length()>=5) {
            getToolkit().beep(); //издава звук
            evt.consume();
        }
        //ограничение да се въвеждат само цифри
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            getToolkit().beep();  //издава звук при въвеждане на буква
            evt.consume();

        }
        
        
        jTextField_Price.getDocument().addDocumentListener(new DocumentListener() {
  @Override
  public void changedUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void removeUpdate(DocumentEvent e) {
    changed();
  }
  @Override
  public void insertUpdate(DocumentEvent e) {
    changed();
  }});
    }//GEN-LAST:event_jTextField_PriceKeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        AddProduct p1 = new AddProduct();
        p1.setSize(1000, 500);
        p1.setLocation(0, 0);

        Panel11.removeAll();
        Panel11.add(p1,BorderLayout.AFTER_LAST_LINE);
        Panel11.revalidate();
        Panel11.repaint();

        jButton_save.setEnabled(false);
        
        jTextField_IdProducts.setEditable(false);

        try
        {
            Connection con;
            Statement st;
            ResultSet rs;

            Class.forName("sun.jdbc.odbc.JdbcOdbcDriver");
            con=DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system?characterEncoding=utf8", "root","");
            st=con.createStatement();
            rs=st.executeQuery("select max(id) from products");

            int i=100;

            while (rs.next())
            {

                i=rs.getInt(1)+1;

            }

            jTextField_IdProducts.setText(""+i);
            con.close();
            st.close();
            rs.close();
        }
        catch (ClassNotFoundException | SQLException e)
        {
        }
    }//GEN-LAST:event_jButton1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox JComboBox_Category;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton_save;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9dsfgbsdfgbsdfg;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea_Information;
    private javax.swing.JTextField jTextField_Brand;
    public static javax.swing.JTextField jTextField_IdProducts;
    private javax.swing.JTextField jTextField_Name;
    private javax.swing.JTextField jTextField_Pieces;
    private javax.swing.JTextField jTextField_Price;
    // End of variables declaration//GEN-END:variables
}
