/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessmanagersystem;

import static fitnessmanagersystem.AddAdministrator1.jTextField_idADMIN;
import static fitnessmanagersystem.OpenWindowClient.jPanel1asdasdasda;
import static fitnessmanagersystem.OpenWindowClient.jTextField_IdClient11;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.event.ItemEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.Date;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.JTextField;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;

/**
 *
 * @author DISHLIEV
 */
public class FitnessCards extends javax.swing.JPanel {
 private Object resultSet;
   
    private Object st;
    private Object rt;
    private Object request;
    private Object con;
    /**
     * Creates new form FitnessCards
     */
    public FitnessCards() {
        initComponents();
               Fillcombo();
    }
    
      
     public Connection getConnection()
   {
      
       Connection con;
    
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system?characterEncoding=utf8", "root","");
           //
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
     public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
          if((st.executeUpdate(query)) == 1)
          {

               
           //    JOptionPane.showMessageDialog(null, "Данните са "+message+" Успешно!");
           }else{
            //   JOptionPane.showMessageDialog(null, "Данните не са "+message);
          }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }

  public class Function{
       
       Connection con = null;
       ResultSet rs = null;
       PreparedStatement ps = null;
      
       
       
       public ResultSet find(String s){
           try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system?characterEncoding=utf8", "root","");

        
ps = con.prepareStatement("SELECT * FROM `fitness_cards` WHERE `type` = ? ");

           ps.setString(1, s);
         
           
          
           rs = ps.executeQuery();
           }
           catch(Exception ex){
               JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs;
       }
 
      
    } 
  
private void Fillcombo(){
 
    try{
         
        Connection con = getConnection();
           Statement st;
         ResultSet rs;
         
               String sql="SELECT * from fitness_cards";
    st=con.prepareStatement(sql);
    rs=st.executeQuery(sql);
    
      
          
           while(rs.next()){
    String card=rs.getString("type");
    jComboBox_typeCard1111.addItem(card);
           }
    
    }catch(Exception e){
    }}

    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox_typeCard1111 = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jTextField_visitsCards = new javax.swing.JTextField();
        jTextField_price = new javax.swing.JTextField();
        jTextField_days = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1asdasdsssssss = new javax.swing.JButton();
        jButton3sadgvasssssssss = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(400, 300));

        jComboBox_typeCard1111.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBox_typeCard1111ItemStateChanged(evt);
            }
        });
        jComboBox_typeCard1111.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox_typeCard1111ActionPerformed(evt);
            }
        });

        jLabel1.setText("Вид карта:");

        jLabel2.setText("Посещения:");

        jLabel3.setText("Цена:");

        jTextField_visitsCards.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_visitsCardsKeyTyped(evt);
            }
        });

        jLabel4.setText("Период на валидност (в дни):");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 11)); // NOI18N
        jLabel5.setText("Фитнес карта");

        jButton1asdasdsssssss.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\Untitled-28-128.png")); // NOI18N
        jButton1asdasdsssssss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1asdasdsssssssActionPerformed(evt);
            }
        });

        jButton3sadgvasssssssss.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\cancel.png")); // NOI18N
        jButton3sadgvasssssssss.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3sadgvasssssssssActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jButton3sadgvasssssssss)
                            .addGap(87, 87, 87)
                            .addComponent(jButton1asdasdsssssss))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jLabel1)
                                .addComponent(jLabel3)
                                .addComponent(jLabel4)
                                .addComponent(jLabel2))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jComboBox_typeCard1111, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jTextField_days)
                                    .addComponent(jTextField_visitsCards)
                                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, 186, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGap(0, 28, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jComboBox_typeCard1111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField_visitsCards, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_days, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField_price, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1asdasdsssssss)
                    .addComponent(jButton3sadgvasssssssss))
                .addContainerGap(57, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox_typeCard1111ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBox_typeCard1111ItemStateChanged
         FitnessCards.Function f = new FitnessCards.Function();
ResultSet rs = null;

     String visits = "visits";
String periodDays="periodDays";
String price="price";


rs = f.find(jComboBox_typeCard1111.getSelectedItem().toString());

try{
    if(rs.next()){
               Integer x = Integer.valueOf(rs.getString(visits));
    if(x==-1){
    jTextField_visitsCards.setText("неограничени");
    }else{
    jTextField_visitsCards.setText(rs.getString("visits"));
    }
    
     
        
      jTextField_days.setText(rs.getString("periodDays"));
  
            jTextField_price.setText(rs.getString("price"));
  
       
            
     
          
     
   
    }
    else{
     JOptionPane.showMessageDialog(null, "Не е намерен!");
    }
}catch(  SQLException | NumberFormatException | HeadlessException ex){
     JOptionPane.showMessageDialog(null, ex.getMessage());
    
}  
        
    
        ((JTextField) jComboBox_typeCard1111.getEditor().getEditorComponent()).getDocument().addDocumentListener(new DocumentListener() {
  @Override
  public void changedUpdate(DocumentEvent e) {
    AddClient.changed1();
  }
  @Override
  public void removeUpdate(DocumentEvent e) {
AddClient.changed1();
  }
  @Override
  public void insertUpdate(DocumentEvent e) {
  AddClient.changed1();
  }});
  
    }//GEN-LAST:event_jComboBox_typeCard1111ItemStateChanged

    private void jComboBox_typeCard1111ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox_typeCard1111ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox_typeCard1111ActionPerformed

    private void jTextField_visitsCardsKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_visitsCardsKeyTyped
  
    }//GEN-LAST:event_jTextField_visitsCardsKeyTyped

    private void jButton1asdasdsssssssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1asdasdsssssssActionPerformed

              
   Date date = new Date();
Format formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date1 = formatter.format(date);      
        
        SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy");
Calendar c = Calendar.getInstance();
c.setTime(new Date()); // Now use today date.



     
           
        
          String visits11=jTextField_visitsCards.getText();    
     
@SuppressWarnings("UnusedAssignment")
       String visits111 = "-1";
       if(!Objects.equals(visits11, "неограничени")){
    
     visits111 = jTextField_visitsCards.getText(); 
       }else{
       visits111 = "-1";
       }
       
String s=jTextField_days.getText();      
        Integer s1=Integer.valueOf(s);
c.add(Calendar.DATE, s1); // Adding days
String output = sdf.format(c.getTime());

Connection connection;
                    PreparedStatement ps;
                    try {
                        connection = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system", "root", "");
                        ps = connection.prepareStatement("SELECT `id` FROM `fitness_clients_cards` WHERE `id` = ? ");
                        ps.setString(1, jTextField_IdClient11.getText());
                      
                        ResultSet result = ps.executeQuery();
                        if(result.next()){
                            
                              String query1 =
        "UPDATE `clients` SET `admin2` ='"+date1+"' WHERE `id` = "+jTextField_IdClient11.getText();
              
          executeSQlQuery(query1,"");
        
        String query = "UPDATE `fitness_clients_cards` SET `typeCliendCard`='"+jComboBox_typeCard1111.getSelectedItem().toString()+"',`visits`='"+visits111+"',`periodDays`='"+output+"',`price`='"+jTextField_price.getText()+"' WHERE `id` = "+jTextField_IdClient11.getText();
       executeSQlQuery(query, "");
                           
                            
                        }
                        else{
                            
                             String query7 =
                    "INSERT INTO `fitness_clients_cards`(`id`,`typeCliendCard`,`visits`,`periodDays`,`price`) VALUES ('"
                  +jTextField_IdClient11.getText()+
                    "','"+jComboBox_typeCard1111.getSelectedItem().toString()+                
                    "','"+visits111+
                    "','"+output+
                    "','"+jTextField_price.getText()+
               "')"; 
      
             executeSQlQuery(query7,"");
             
       


      String query6 =
        "UPDATE `clients` SET `admin2` ='"+date1+"' WHERE `id` = "+jTextField_IdClient11.getText();
                   executeSQlQuery(query6,"");           
                           
                        }
                        
                    } catch (SQLException ex) {
                     //   Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                        
                    }    

   
        

    }//GEN-LAST:event_jButton1asdasdsssssssActionPerformed

    private void jButton3sadgvasssssssssActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3sadgvasssssssssActionPerformed
        OpenClientCardPanel p1 = new OpenClientCardPanel();
    p1.setSize(1000, 500);
    p1.setLocation(0, 0);
    
    jPanel1asdasdasda.setLayout(new GridLayout(0,1));
    jPanel1asdasdasda.removeAll();
    jPanel1asdasdasda.add(p1,BorderLayout.PAGE_END);
    jPanel1asdasdasda.revalidate();
    jPanel1asdasdasda.repaint();
    }//GEN-LAST:event_jButton3sadgvasssssssssActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1asdasdsssssss;
    public static javax.swing.JButton jButton3sadgvasssssssss;
    public static javax.swing.JComboBox jComboBox_typeCard1111;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    public static javax.swing.JTextField jTextField_days;
    public static javax.swing.JTextField jTextField_price;
    public static javax.swing.JTextField jTextField_visitsCards;
    // End of variables declaration//GEN-END:variables
}
