/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessmanagersystem;

import static fitnessmanagersystem.GUI.jButton3asdvavsda;
import static fitnessmanagersystem.GUI.jButton_Administrators;
import static fitnessmanagersystem.GUI.jButton_makecard;
import static fitnessmanagersystem.GUI.jMenu5;
import static fitnessmanagersystem.GUI.jMenu8;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/**
 *
 * @author DISHLIEV
 */
public class Login extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField1username = new javax.swing.JTextField();
        jPasswordField1password = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Име:");

        jLabel2.setText("Парола:");

        jPasswordField1password.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                jPasswordField1passwordKeyPressed(evt);
            }
        });

        jButton1.setText("Вход");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel2)
                            .addComponent(jLabel1))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField1username)
                            .addComponent(jPasswordField1password, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(165, 165, 165)
                        .addComponent(jButton1)))
                .addContainerGap(111, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(74, 74, 74)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1username, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1password, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addComponent(jButton1)
                .addContainerGap(78, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

           Connection connection;
        PreparedStatement ps;
        try {
            connection = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system", "root", "");
            ps = connection.prepareStatement("SELECT `username`, `password` FROM `admins` WHERE `username` = ? AND `password` = ?");
            ps.setString(1, jTextField1username.getText());
            ps.setString(2, String.valueOf(jPasswordField1password.getPassword()));
            ResultSet result = ps.executeQuery();
            if (result.next()) {

                this.dispose();

                GUI frame = new GUI();
                frame.pack();
                frame.setLocationRelativeTo(null);
                frame.setVisible(true);

                jButton_Administrators.setEnabled(false);
                jButton_makecard.setEnabled(false);
                jButton3asdvavsda.setEnabled(false);
                jMenu8.setEnabled(false);
                jMenu5.setEnabled(false);

            } else {

                try {
                    connection = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system", "root", "");
                    ps = connection.prepareStatement("SELECT `username`, `password` FROM `global_admin` WHERE `username` = ? AND `password` = ?");
                    ps.setString(1, jTextField1username.getText());
                    ps.setString(2, String.valueOf(jPasswordField1password.getPassword()));
                    ResultSet result1 = ps.executeQuery();
                    if (result1.next()) {

                        this.dispose();

                        GUI frame = new GUI();
                        frame.pack();
                        frame.setLocationRelativeTo(null);
                        frame.setVisible(true);

                    } else {

                        try {
                            connection = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system", "root", "");
                            ps = connection.prepareStatement("SELECT `username`, `password` FROM `trainer-login` WHERE `username` = ? AND `password` = ?");
                            ps.setString(1, jTextField1username.getText());
                            ps.setString(2, String.valueOf(jPasswordField1password.getPassword()));
                            ResultSet result2 = ps.executeQuery();
                            if (result2.next()) {

                                this.dispose();

                                GUI frame = new GUI();
                                frame.pack();
                                frame.setLocationRelativeTo(null);
                                frame.setVisible(true);

                            } else {
                                JOptionPane.showMessageDialog(null, "Грешно име или парола!", "Грешка", JOptionPane.ERROR_MESSAGE);

                            }

                        } catch (SQLException ex) {
                            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);

                        }
                    }

                } catch (SQLException ex) {
                    Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);

                }

            }

        } catch (SQLException ex) {
            Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);

        }


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jPasswordField1passwordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jPasswordField1passwordKeyPressed
      if(evt.getKeyCode() == KeyEvent.VK_ENTER)
            {
                 Connection connection;
        PreparedStatement ps;
                    try {
                        connection = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system", "root", "");
                        ps = connection.prepareStatement("SELECT `username`, `password` FROM `admins` WHERE `username` = ? AND `password` = ?");
                        ps.setString(1, jTextField1username.getText());
                        ps.setString(2, String.valueOf(jPasswordField1password.getPassword()));
                        ResultSet result = ps.executeQuery();
                        if(result.next()){
                            
                            this.dispose();
                            
                        
                    
                              GUI frame = new GUI(); 
                                frame.pack();
                                frame.setLocationRelativeTo(null);
                                frame.setVisible(true);

                        }
                        else{
                        
                            
                               try {
                        connection = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system", "root", "");
                        ps = connection.prepareStatement("SELECT `username`, `password` FROM `login-globaladmin` WHERE `username` = ? AND `password` = ?");
                        ps.setString(1, jTextField1username.getText());
                        ps.setString(2, String.valueOf(jPasswordField1password.getPassword()));
                        ResultSet result1 = ps.executeQuery();
                        if(result1.next()){
                            
                            this.dispose();
                            
                        
                    
                              GUI frame = new GUI(); 
                                frame.pack();
                                frame.setLocationRelativeTo(null);
                                frame.setVisible(true);

                        }
                        else{
                            
                            
                             try {
                        connection = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system", "root", "");
                        ps = connection.prepareStatement("SELECT `username`, `password` FROM `trainer-login` WHERE `username` = ? AND `password` = ?");
                        ps.setString(1, jTextField1username.getText());
                        ps.setString(2, String.valueOf(jPasswordField1password.getPassword()));
                        ResultSet result2 = ps.executeQuery();
                        if(result2.next()){
                            
                            this.dispose();
                            
                        
                    
                              GUI frame = new GUI(); 
                                frame.pack();
                                frame.setLocationRelativeTo(null);
                                frame.setVisible(true);

                        }
                        else{
                             JOptionPane.showMessageDialog(null,"Грешно име или парола!","Грешка",JOptionPane.ERROR_MESSAGE);
                            
                        }
                      
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);                                
  
     }
                        }
                      
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                     
  
     }
                        
                        }
                        
                    } catch (SQLException ex) {
                        Logger.getLogger(GUI.class.getName()).log(Level.SEVERE, null, ex);
                        
                    } 
            }
        
        
    }//GEN-LAST:event_jPasswordField1passwordKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              //  new Login().setVisible(true);
                Login frame = new Login();
                  frame.pack();
                    frame.setLocationRelativeTo(null);
                     frame.setVisible(true);
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1password;
    private javax.swing.JTextField jTextField1username;
    // End of variables declaration//GEN-END:variables
}
