/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessmanagersystem;

import static fitnessmanagersystem.BirthDays.email;
import static fitnessmanagersystem.GUI.Panel11;
import static fitnessmanagersystem.GUI.administrator;
import static fitnessmanagersystem.OpenClientCardPanel.ascajLabel10;
import static fitnessmanagersystem.OpenClientCardPanel.jLabel6sdssssssssssssss;
import static fitnessmanagersystem.OpenClientCardPanel.jLabel7dvv;
import static fitnessmanagersystem.OpenClientCardPanel.jLabel9dddddddddddddd;
import static fitnessmanagersystem.SendEmail1.txtto1;
import java.awt.BorderLayout;
import java.awt.GridLayout;
import java.awt.HeadlessException;
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.Format;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.Objects;
import javax.swing.JOptionPane;
import javax.swing.JToggleButton;
import javax.swing.table.TableModel;

/**
 *
 * @author DISHLIEV
 */
public class OpenWindowClient extends javax.swing.JPanel {

    /**
     * Creates new form OpenWindowClient
     */
    public OpenWindowClient() {
        initComponents();
        
        
    }
       
     public Connection getConnection()
   {
      
       Connection con;
    
       try {
           con = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system?characterEncoding=utf8", "root","");
           //
           return con;
       } catch (Exception e) {
           e.printStackTrace();
           return null;
       }
   }
     public void executeSQlQuery(String query, String message)
   {
       Connection con = getConnection();
       Statement st;
       try{
           st = con.createStatement();
          if((st.executeUpdate(query)) == 1)
          {

               
               JOptionPane.showMessageDialog(null, "Данните са "+message+" Успешно!");
           }else{
               JOptionPane.showMessageDialog(null, "Данните не са "+message);
          }
       }catch(Exception ex){
           ex.printStackTrace();
       }
   }
     
     /*
 public class Function{
       
       Connection con = null;
       ResultSet rs = null;
       PreparedStatement ps = null;
      
       
       
       public ResultSet find(String s){
           try{
           con = DriverManager.getConnection("jdbc:mysql://localhost/fitness-manager-system?characterEncoding=utf8", "root","");

        
ps = con.prepareStatement("SELECT * FROM `clientscards` WHERE `id` =?");

           ps.setString(1, s);
         
           
          
           rs = ps.executeQuery();
           }
           catch(Exception ex){
               JOptionPane.showMessageDialog(null, ex.getMessage());
           }
           return rs;
       }
 
      
    } 
  */
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextField_IdClient11 = new javax.swing.JTextField();
        jTextField_FirstName111 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jTextField_LastName = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jTextField_Emailaa = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField_Age = new javax.swing.JTextField();
        jTextField_Telephone11 = new javax.swing.JTextField();
        jTextField_Street111 = new javax.swing.JTextField();
        jComboBox_City11 = new javax.swing.JComboBox();
        jLabel9 = new javax.swing.JLabel();
        jComboBox_Sex11 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jCheckBox1асджсд = new javax.swing.JCheckBox();
        jLabel1000 = new javax.swing.JLabel();
        jPanel1asdasdasda = new javax.swing.JPanel();
        jToggleButton1 = new javax.swing.JToggleButton();
        jButton4 = new javax.swing.JButton();

        jLabel3.setText("Фамилия:");

        jLabel4.setText("Дата на раждане:");

        jTextField_FirstName111.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_FirstName111KeyTyped(evt);
            }
        });

        jLabel6.setText("Град:");

        jLabel7.setText("ул.");

        jLabel1.setText("ID номер:");

        jLabel2.setText("Име:");

        jTextField_Age.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_AgeKeyTyped(evt);
            }
        });

        jTextField_Telephone11.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                jTextField_Telephone11KeyTyped(evt);
            }
        });

        jComboBox_City11.setEditable(true);
        jComboBox_City11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Айтос ", "Асеновград ", "Ахтопол ", "Балчик ", "Банкя", "Банско ", "Батак ", "Белене", "Белица ", "Белослав  ", "Берковица ", "Битоля ", "Благоевград ", "Ботевград", "Брацигово ", "Брезник ", "Бургас ", "Бяла ", "Варна ", "Велес", "Велики Преслав ", "Велико Търново ", "Велинград ", "Видин ", "Враца ", "Вършец ", "Габрово ", "Гевгели", "Горна Оряховица", "Гоце Делчев ", "Гюмюрджина ", "Дедеагач ", "Демир Хисар ", "Димитровград ", "Добрич ", "Дойран ", "Долна Баня ", "Долна Оряховица ", "Долни Дъбник ", "Драма ", "Дупница ", "Елена ", "Исперих ", "Ихтиман ", "Кавала ", "Каварна ", "Казанлък ", "Калофер ", "Карлово ", "Карнобат ", "Кешан ", "Китен ", "Козлодуй ", "Копривщица ", "Костенец ", "Костур ", "Котел ", "Кресна", "Крушево ", "Ксанти ", "Кукуш ", "Кърджали ", "Кюстендил ", "Лерин ", "Ловеч ", "Лозенград ", "Лом ", "Люле Бургас ", "Мадан ", "Мелник " }));

        jLabel9.setText("Телефон:");

        jComboBox_Sex11.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "мъж", "жена" }));

        jLabel8.setText("Пол:");

        jLabel5.setText("Емайл:");

        jButton1.setText("назад");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\gnome_media_floppy.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\cancel.png")); // NOI18N
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jCheckBox1асджсд.setText("редактиране");
        jCheckBox1асджсд.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jCheckBox1асджсдMouseClicked(evt);
            }
        });
        jCheckBox1асджсд.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1асджсдActionPerformed(evt);
            }
        });

        jLabel1000.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jPanel1asdasdasda.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        javax.swing.GroupLayout jPanel1asdasdasdaLayout = new javax.swing.GroupLayout(jPanel1asdasdasda);
        jPanel1asdasdasda.setLayout(jPanel1asdasdasdaLayout);
        jPanel1asdasdasdaLayout.setHorizontalGroup(
            jPanel1asdasdasdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 349, Short.MAX_VALUE)
        );
        jPanel1asdasdasdaLayout.setVerticalGroup(
            jPanel1asdasdasdaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 302, Short.MAX_VALUE)
        );

        jToggleButton1.setText("карта");
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });

        jButton4.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\email-send-icon-small.png")); // NOI18N
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(143, 143, 143)
                        .addComponent(jButton1)
                        .addGap(66, 66, 66)
                        .addComponent(jButton2)
                        .addGap(97, 97, 97)
                        .addComponent(jButton3))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel9)
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(jLabel8)
                            .addComponent(jLabel6)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jTextField_Street111, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jTextField_Emailaa, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jTextField_IdClient11, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Telephone11, javax.swing.GroupLayout.DEFAULT_SIZE, 193, Short.MAX_VALUE)
                            .addComponent(jComboBox_Sex11, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jTextField_Age)
                            .addComponent(jTextField_FirstName111)
                            .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, 140, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jComboBox_City11, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(22, 22, 22)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jCheckBox1асджсд))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 54, 54)
                                .addComponent(jLabel1000, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1asdasdasda, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jToggleButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(111, 111, 111)
                                .addComponent(jButton4)))
                        .addGap(0, 181, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel1)
                            .addComponent(jTextField_IdClient11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jCheckBox1асджсд))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(22, 22, 22)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel2)
                                    .addComponent(jTextField_FirstName111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel3)
                                    .addComponent(jTextField_LastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jLabel4)
                                    .addComponent(jTextField_Age, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(15, 15, 15)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jComboBox_Sex11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jTextField_Telephone11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jTextField_Emailaa, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel5))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                            .addComponent(jComboBox_City11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jLabel6)))
                                    .addComponent(jLabel9))
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTextField_Street111, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addComponent(jPanel1asdasdasda, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jToggleButton1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel1000, javax.swing.GroupLayout.PREFERRED_SIZE, 168, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(38, 38, 38)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton2)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(10, 10, 10))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField_FirstName111KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_FirstName111KeyTyped
        //максимален брой символи
        if(jTextField_FirstName111.getText().length()>=10) {
            getToolkit().beep(); //издава звук
            evt.consume();
        }
        //ограничение да се въвежда само букви
        char c = evt.getKeyChar();
        if(!(Character.isLetter(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            getToolkit().beep(); //издава звук
            evt.consume();}
    }//GEN-LAST:event_jTextField_FirstName111KeyTyped

    private void jTextField_AgeKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_AgeKeyTyped
        if(jTextField_Age.getText().length()>=2) {
            getToolkit().beep(); //издава звук
            evt.consume();
        }

        //ограничение да се въвеждат само цифри
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            getToolkit().beep(); //издава звук при въвеждане на буква
            evt.consume();
        }
    }//GEN-LAST:event_jTextField_AgeKeyTyped

    private void jTextField_Telephone11KeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTextField_Telephone11KeyTyped
        if(jTextField_Telephone11.getText().length()>=10) {
            getToolkit().beep(); //издава звук
            evt.consume();
        }
        //ограничение да се въвеждат само цифри
        char c = evt.getKeyChar();
        if(!(Character.isDigit(c)||(c==KeyEvent.VK_BACK_SPACE)||c==KeyEvent.VK_DELETE)){
            getToolkit().beep();  //издава звук при въвеждане на буква
            evt.consume();

        }
    }//GEN-LAST:event_jTextField_Telephone11KeyTyped

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        SearchClient p1 = new SearchClient();
    p1.setSize(1000, 500);
    p1.setLocation(0, 0);
    
    Panel11.removeAll();
    Panel11.add(p1,BorderLayout.AFTER_LAST_LINE);
    Panel11.revalidate();
    Panel11.repaint();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        HomePanel p1 = new HomePanel();
                            p1.setSize(949, 100);
                            p1.setLocation(0, 0);
                            
                            Panel11.setLayout(new GridLayout(0,1));
                            Panel11.removeAll();
                            Panel11.add(p1,BorderLayout.PAGE_END);
                            Panel11.revalidate();
                            Panel11.repaint();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jCheckBox1асджсдMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jCheckBox1асджсдMouseClicked
    boolean isSelected = jCheckBox1асджсд.isSelected();

if(isSelected ){
     
     
        jTextField_IdClient11.setEditable(true);
     jTextField_FirstName111.setEditable(true);
        jTextField_LastName.setEditable(true);
        jTextField_Age.setEditable(true);
        jComboBox_Sex11.setEditable(true);
        jTextField_Telephone11.setEditable(true);
        jTextField_Emailaa.setEditable(true);
    jComboBox_City11.setEditable(true);
    jTextField_Street111.setEditable(true);
    

 //jCheckBox1.setSelected(false);
} else {
     
      
        jTextField_IdClient11.setEditable(false);
         jTextField_FirstName111.setEditable(true);
        jTextField_LastName.setEditable(false);
        jTextField_Age.setEditable(false);
        jComboBox_Sex11.setEditable(false);
        jTextField_Telephone11.setEditable(false);
            jTextField_Emailaa.setEditable(false);
    jComboBox_City11.setEditable(isSelected);
              jTextField_Street111.setEditable(false);
   
           
        jCheckBox1асджсд.setEnabled(true);
   jCheckBox1асджсд.setSelected(false);
 
  
}
    }//GEN-LAST:event_jCheckBox1асджсдMouseClicked

    private void jCheckBox1асджсдActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1асджсдActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1асджсдActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Date date = new Date();
Format formatter = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        String date1 = formatter.format(date);
       
      
        
        
        String query99 = "UPDATE `clients` SET `firstName`='"+jTextField_FirstName111.getText()+"',`lastName`='"+jTextField_LastName.getText()+"',`dateOfBirdth`='"+jTextField_Age.getText()+"',`sex`='"+jComboBox_Sex11.getSelectedItem().toString()+"',`telephone`='"+jTextField_Telephone11.getText()+"',`city`='"+jComboBox_City11.getSelectedItem().toString()+"',`email`='"+jTextField_Emailaa.getText()+"',`street`='"+jTextField_Street111.getText()+"',`admin2`='"+administrator+" / "+date1+"' WHERE `id` = "+jTextField_IdClient11.getText();
        executeSQlQuery(query99, "Променени");
   
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
  
    OpenClientCardPanel p1 = new OpenClientCardPanel();
    p1.setSize(1000, 500);
    p1.setLocation(0, 0);
    
    jPanel1asdasdasda.setLayout(new GridLayout(0,1));
    jPanel1asdasdasda.removeAll();
    jPanel1asdasdasda.add(p1,BorderLayout.PAGE_END);
    jPanel1asdasdasda.revalidate();
    jPanel1asdasdasda.repaint();
   
   
   
          OpenClientCardPanel.Function f = new OpenClientCardPanel.Function();
ResultSet rs = null;



rs = f.find(jTextField_IdClient11.getText());

try{
    if(rs.next()){
     
   String visits2 = "-1";
       if(visits2.equals(rs.getString("visits"))){
    
     jLabel6sdssssssssssssss.setText(rs.getString("periodDays"));
  
            jLabel9dddddddddddddd.setText("неограничени");
       }else{
      jLabel6sdssssssssssssss.setText(rs.getString("periodDays"));
  
            jLabel9dddddddddddddd.setText(rs.getString("visits"));
       }
    

  
    }
    else{
  
    }
}catch(  SQLException | NumberFormatException | HeadlessException ex){
     JOptionPane.showMessageDialog(null, ex.getMessage());
    
}  

          OpenClientCardPanel.Function1 f1 = new OpenClientCardPanel.Function1();




rs = f1.find(jTextField_IdClient11.getText());

try{
    if(rs.next()){
     
  
      ascajLabel10.setText(rs.getString("periodDays"));
  
            jLabel7dvv.setText(rs.getString("minutes"));
       }
    

  
    
    else{
  
    }
}catch(  SQLException | NumberFormatException | HeadlessException ex){
     JOptionPane.showMessageDialog(null, ex.getMessage());
    
}  
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
    

            SendEmail1 p1 = new SendEmail1();
            p1.setSize(1000, 500);
            p1.setLocation(0, 0);

            Panel11.setLayout(new GridLayout(0,1));
            Panel11.removeAll();
            Panel11.add(p1,BorderLayout.PAGE_END);
            Panel11.revalidate();
            Panel11.repaint();

            

            BirthDays.email = jTextField_Emailaa.getText();

            txtto1.setText(email);
     
    }//GEN-LAST:event_jButton4ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1асджсд;
    public static javax.swing.JComboBox jComboBox_City11;
    public static javax.swing.JComboBox jComboBox_Sex11;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel1000;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    public static javax.swing.JPanel jPanel1asdasdasda;
    public static javax.swing.JTextField jTextField_Age;
    public static javax.swing.JTextField jTextField_Emailaa;
    public static javax.swing.JTextField jTextField_FirstName111;
    public static javax.swing.JTextField jTextField_IdClient11;
    public static javax.swing.JTextField jTextField_LastName;
    public static javax.swing.JTextField jTextField_Street111;
    public static javax.swing.JTextField jTextField_Telephone11;
    private javax.swing.JToggleButton jToggleButton1;
    // End of variables declaration//GEN-END:variables
}
