/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package fitnessmanagersystem;


import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.GraphicsConfiguration;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import static java.awt.image.ImageObserver.WIDTH;
import java.io.ByteArrayInputStream;
import java.io.File;
import java.io.IOException;
import java.sql.Blob;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JPanel;
import org.opencv.core.Core;
import static org.opencv.core.Core.max;
import org.opencv.core.Mat;
import org.opencv.core.MatOfByte;
import org.opencv.highgui.Highgui;
import org.opencv.highgui.VideoCapture;


import javax.swing.*;
import java.awt.Image;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.image.ImageObserver;
import javax.swing.event.ChangeListener;
import javax.swing.event.ChangeEvent;
/**
 *
 * @author DISHLIEV
 */
public class Picture extends javax.swing.JFrame {

    /**
     * Creates new form Picture
     */
    public Picture() {
        initComponents();
    }

  
  
    private DaemonThread myThread = null;
    int count = 0;
    VideoCapture webSource = null;

    Mat frame = new Mat();
    MatOfByte mem = new MatOfByte();
    
 public class DaemonThread implements Runnable
    {
    protected volatile boolean runnable = false;

    @Override
    public  void run()
    {
        synchronized(this)
        {
            while(runnable)
            {
                if(webSource.grab())
                {
		    	try
                        {
                             
          
                            webSource.retrieve(frame);
			    Highgui.imencode(".bmp", frame, mem);
                            
			    Image im = ImageIO.read(new ByteArrayInputStream(mem.toArray()));
                               
			    BufferedImage buff = (BufferedImage) im;
                        
			    Graphics g=jPanel1picture.getGraphics();
                   
                            
     
			      if (g.drawImage(buff, 0, 0, getWidth(), getHeight()-0 , 0, 0, buff.getWidth(), buff.getHeight(), null)) {
                        if (runnable == false) {
                            System.out.println("Paused ..... ");
                            this.wait();
                        }
                    }
                } catch (   IOException | InterruptedException ex) {
                    System.out.println("Error");
                }
            }else{
                System.out.println("error");
            }
        }
    }
}}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1picture = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jButton1asdvasdvfasdfvsdvfsdvfsdvfs = new javax.swing.JButton();
        jButton1sdvsdsvdvsvdsvdvs1 = new javax.swing.JButton();
        jButton2asdvasdv = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1picture.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jLabel1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\camerafonnn.png")); // NOI18N

        javax.swing.GroupLayout jPanel1pictureLayout = new javax.swing.GroupLayout(jPanel1picture);
        jPanel1picture.setLayout(jPanel1pictureLayout);
        jPanel1pictureLayout.setHorizontalGroup(
            jPanel1pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1pictureLayout.setVerticalGroup(
            jPanel1pictureLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel1.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        jButton1asdvasdvfasdfvsdvfsdvfsdvfs.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\play_button.png")); // NOI18N
        jButton1asdvasdvfasdfvsdvfsdvfsdvfs.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1asdvasdvfasdfvsdvfsdvfsdvfsActionPerformed(evt);
            }
        });

        jButton1sdvsdsvdvsvdsvdvs1.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\snimka.png")); // NOI18N
        jButton1sdvsdsvdvsvdsvdvs1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1sdvsdsvdvsvdsvdvs1ActionPerformed(evt);
            }
        });

        jButton2asdvasdv.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\gnome_media_floppy.png")); // NOI18N
        jButton2asdvasdv.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2asdvasdvActionPerformed(evt);
            }
        });

        jButton2.setIcon(new javax.swing.ImageIcon("C:\\Users\\DISHLIEV\\Documents\\1\\FitnessManagerSystem\\icons\\cancel.png")); // NOI18N
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(170, 170, 170)
                .addComponent(jButton1asdvasdvfasdfvsdvfsdvfsdvfs)
                .addGap(34, 34, 34)
                .addComponent(jButton1sdvsdsvdvsvdsvdvs1)
                .addGap(36, 36, 36)
                .addComponent(jButton2asdvasdv)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton1sdvsdsvdvsvdsvdvs1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2asdvasdv, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton1asdvasdvfasdfvsdvfsdvfsdvfs, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1picture, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2asdvasdvActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2asdvasdvActionPerformed
        JFileChooser chooser = new JFileChooser();
        int returnVal = chooser.showSaveDialog(this);

        if (returnVal == JFileChooser.APPROVE_OPTION) {
            File file = chooser.getSelectedFile();
         
            Highgui.imwrite(file.getPath(), frame);
            
        } else {
            System.out.println("File access cancelled by user.");
        }
       
        
  webSource =new VideoCapture(0);
  myThread = new Picture.DaemonThread();
            Thread t = new Thread(myThread);
           t.setDaemon(true);
           myThread.runnable = true;
            t.start();
            
         
       
    }//GEN-LAST:event_jButton2asdvasdvActionPerformed

    private void jButton1sdvsdsvdvsvdsvdvs1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1sdvsdsvdvsvdsvdvs1ActionPerformed
              myThread.runnable = false;
           // webSource.release();
      
         
    }//GEN-LAST:event_jButton1sdvsdsvdvsvdsvdvs1ActionPerformed

    private void jButton1asdvasdvfasdfvsdvfsdvfsdvfsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1asdvasdvfasdfvsdvfsdvfsdvfsActionPerformed
      webSource =new VideoCapture(0);
      myThread = new Picture.DaemonThread();
            Thread t = new Thread(myThread);
            t.setDaemon(true);
           myThread.runnable = true;
            t.start();
            jButton1asdvasdvfasdfvsdvfsdvfsdvfs.setEnabled(true);
            jButton1sdvsdsvdvsvdsvdvs1.setEnabled(true);
            jButton2asdvasdv.setEnabled(true);
    }//GEN-LAST:event_jButton1asdvasdvfasdfvsdvfsdvfsdvfsActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
     
        myThread=null;
        this.dispose();
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        System.loadLibrary(Core.NATIVE_LIBRARY_NAME);
      
        
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Picture.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Picture().setVisible(true);
                
                 
            }}    );
       
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JButton jButton1asdvasdvfasdfvsdvfsdvfsdvfs;
    public static javax.swing.JButton jButton1sdvsdsvdvsvdsvdvs1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton2asdvasdv;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JPanel jPanel1picture;
    // End of variables declaration//GEN-END:variables
}
